# Generated by Django 3.2.5 on 2021-07-14 12:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(verbose_name=datetime.datetime(2021, 7, 14, 12, 15, 41, 778060, tzinfo=utc))),
                ('order_amount', models.FloatField()),
                ('customer_no', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ideep_2_App.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('failed', 'FAILED'), ('paid', 'PAID')], max_length=10)),
                ('order_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ideep_2_App.order')),
            ],
        ),
    ]
