# Generated by Django 3.2.5 on 2021-07-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideep_2_App', '0002_auto_20210716_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=25),
        ),
    ]
